### ISSUE TITLE
☂️ Road to 1.0.0

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents-react#1318]
**This issue is a collection of possible tasks that should be completed before we can release a 1.0.0 version**

## Prerequisites

- [x] UI5 Web Components 1.0.0 release

## Tasks

- [x] Do we need to publish a common js build?
       --> No
       #1450
- [x] We have our components in the `lib` folder and our assets in the `dist` folder - move everything into dist?
      --> Yes, `dist` will be the new folder. Grace period with both `lib` and `dist` folder.
      done with #1356
- [x] Switch from `.npmignore` to `package.json files`
      done with #1356
- [ ] Bump minimum required react version, check downloads of specific react versions
       https://www.npmjs.com/package/react
       --> 16.8.6
- [ ] Support Fiori Horizon (#3026)       

### Components

~- AnalyticalTable: Refactor to use a more modular approach to improve maintenance, DX and probably performance as well~
- [x] ObjectPage: Consolidate API of ObjectPage and DynamicPage (see https://github.com/SAP/ui5-webcomponents-react/issues/1192)
   done with #1782
- [ ] Charts: Improve typings especially for `chartConfig` prop
