### ISSUE TITLE
Merge styles and utils

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents-react#34]
The styles and the utils package are requiring each other, so we duplicate code inside at the moment. Moving forward we want to use the styles from the ui5-webcomponents, so there is no need to keep those packages separate.
--> Merge the `styles` and the `utils` package into a new package `base`.

## ToDos:
- [x] Move Packages into new package `base`
- [x] Adjust Readme
- [x] Adjust npm release scripts
- [ ] Deprecate `styles` and `utils` on npm
- [x] Delete old styles `sap_belize`, `sap_belize_plus` and `sap_belize_hcb`
