### ISSUE TITLE
use ESM Modules for dev scripts

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents-react#701]
Since we are using Node 12.16 or 14 for developing and building UI5 Web Components for React, we can now migrate all internal dev scripts and helper files to native esm modules.

## Todo
We can probably add `"type": "module"` to the top-level package.json, renaming config files (such as .eslintrc.js) to `.cjs`.
- [ ] Mention the required Node-Version in  docs/Guidelines.md (`^12.16 || ^14`)

Migrate the following files to use ESM Modules:
- [ ] `.storybook/main.js`
- [ ] `config/jest.config.js`
- [ ] `config/paths.js`
- [ ] everything under `scripts/*`
- [ ] `shared/tests/serializer/*`
- [ ] `babel.config.js`
- [ ] `packages/base/scripts/cssVariables/parse.js`
- [ ] `packages/main/scripts/create-library-export.js`

## Useful Links
- [Node JS Packages Documentation](https://nodejs.org/api/packages.html)

**Comment by KolCrooks** [comment]
I can do this if you want!

**Comment by MarcusNotheis** [comment]
Sure, I've just assigned this issue to you. Thanks for tackling this one 👍

**Comment by KolCrooks** [comment]
I changed all the files to use ESM Modules but for some reason it has had some unforeseen side effects. When It try and build the code, I get this error.
![image](https://user-images.githubusercontent.com/20110047/95130729-0394be80-072b-11eb-85fc-0c29325bd2d2.png)
It looks like changing the module type has somehow added a second `package/` in the directory URL. I think this is associated with a problem that I found when running tests. In `config/paths.js` it uses `__dirname` but when I run it with the tests, it says that `__dirname` is not defined and errors out.
![image](https://user-images.githubusercontent.com/20110047/95131060-7736cb80-072b-11eb-8b66-3935d9ae7337.png)

You can look at the changes I made here: https://github.com/KolCrooks/ui5-webcomponents-react/commit/b2567f3e20c66d5a2d248fa71396fcd4744ec1e5.
I'm not sure if you want to continue with theses changes to the code because I really don't how to proceed with all of this.

**Comment by MarcusNotheis** [comment]
Hey @KolCrooks,
thanks for starting here. I think we need some more adjustments but we are on a good way:

- [ ] Rename all rollup.config.js to `rollup.config.mjs` (we need that because the package.json files of the single modules do not contain `type: module`
- [ ] Rename `config/paths.js` to `config/paths.mjs`, as well as the `scripts/rollup/configFactory.js` and `scripts/utils.mjs`
- [ ] when importing those files, make sure you add `.mjs` to the import, like: `import rollupConfigFactory from '../../scripts/rollup/configFactory.mjs';`
- [ ] For the missing __dirname, [this might help you](https://nodejs.org/api/esm.html#esm_no_require_exports_module_exports_filename_dirname)

I was playing around with the mentioned changes above and it looked promising. I didn't get it running with node 12, but node 14 was working fine.

**Comment by KolCrooks** [comment]
I think that I created something that builds. I am getting some problems with the `yarn run build:types` stage of the build process but I think that it is just associated with my system environment. On that note, the command `"build:polyfills": "tsc ./src/polyfill/*.ts --outDir ./polyfill --skipLibCheck"` in the base package will only run on linux. I tried it on windows but got errors about not being able to find the file `./src/polyfill/*.ts` so I ended up just running it on WSL.
You can check out the changes here: https://github.com/KolCrooks/ui5-webcomponents-react/tree/ESMDevScripts

**Comment by MarcusNotheis** [comment]
Thanks @KolCrooks,
the build is looking good! Do you want to open a Pull Request so that we can get this over the line?
There are two things I noticed:

- You can change the Babel import in the config factory file:
   ```js
   REPLACE THIS
   import Babel from '@rollup/plugin-babel';
   WITH THIS
   import { babel } from '@rollup/plugin-babel';
   ```
   and remove `const { babel } = Babel;` from line 14.

- Please remove the `package-lock.json` file as we are only using yarn.

There is one more thing regarding the storybook: running `yarn start` is currently throwing an error on my side, but I think this might be related to https://github.com/storybookjs/storybook/issues/11587.

**Comment by MarcusNotheis** [comment]
I think I found a workaround for the Storybook Issue.
1. Discard all changes in the `.storybook/main.js` file and rename it to `.storybook/main.cjs`
2. replace `const PATHS = require('../config/paths');` with `const root = path.resolve(__dirname, '..');`
3. replace all occurrences of `PATHS.root` with `root`

**Comment by KolCrooks** [comment]
@MarcusNotheis Sorry that I am just responding now but I have been really busy recently.

When I had
```
import Babel from '@rollup/plugin-babel';
AS
import { babel } from '@rollup/plugin-babel';
```
It would give an error telling me that I could only use the default import.
![image](https://user-images.githubusercontent.com/20110047/95501928-0d126680-0977-11eb-93ba-7256f8671272.png)
I also made a pull request to merge the changes into the main branch. #720
